### ISSUE TITLE
[Lib] Failed to create book

### ISSUE THREAD

**Issue by alvachien** [alvachien/hih#54]
Error information in Console part:
TypeError: $.toJSON is not a function
    at LibBookAuthor.hih.LibPerson.ToJSONObject (http://192.168.1.110/hih/app/controllers/model.js:2155:66)
    at LibBookAuthor.hih.LibBookAuthor.ToJSONObject (http://192.168.1.110/hih/app/controllers/model.js:2369:60)
    at LibBook.hih.LibBook.ToJSONObject (http://192.168.1.110/hih/app/controllers/model.js:2520:37)
    at LibBook.hih.LibBook.ToJSON (http://192.168.1.110/hih/app/controllers/model.js:2539:28)

**Comment by alvachien** [comment]
Fixed in commit f14f112 .
